name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dahlia/actions/yajsv@master
      with:
        schema: table.schema.yaml
        documents: tables/*.yaml
    - uses: zbeekman/EditorConfig-Action@master
    - uses: ibiqlik/action-yamllint@v3
      with:
        strict: yes
